//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploMVVM.wpf.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdUsuario { get; set; }
        public string Clave { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Existencia { get; set; }
    }
}
